- title: "biotanik origin color"
  image: "/img/united-origin.jpg"
  description: " Après plusieurs années de  recherche , le laboratoire Inéal avec l'aide de spécialistes a crée biotanik origin color."

- title: "Coloration sans ammoniaque et sans Paraphénylènediamine"
  image: "/img/the--virgin-color.jpg"
  description: "Formulée avec des ingrédients végétaux et biologiques et éco-certifiée de haute qualité , spécialement sélectionnées pour leurs puissantes propriétés régénérantes , conservatrices et anti-âge."

- title: "Nook difference Hair Care"
  image: "/img/nook.jpg"
  description: "Nature, Equilibre et Harmonie. Cette gamme représente la  parfaite combinaison. Traite les cheveux et le cuir chevelu avec douceur en améliorant leur beauté et en intervenant sur les anomalies les plus courantes . Elle consiste à les ramener à leur équilibre originel."

- title: "100% Vegan"
  image: "/img/solar.jpg"
  description: "La nouvelle gamme de produits, 100% vegan, formulée avec au moins 90% de produit d'origine naturelle, pour les soins quotidiens de toute la famille. Les précieux ingrédients biologiques qui composent chaque produit , riches en propriétés anti-oxydantes et ultra hydratantes , protègent et préservent la santé et la beauté des cheveux et des peaux exposés au soleil , au vent , aux facteurs environnementaux , au stress et à la pollution , en été et tout au long de l'année"
